CustomerManagement App/EmployeePortal-UI/Controllers/AccountViewsController.cs
using EmployeePortal_UI.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmployeePortal_UI.Controllers
{
    public class AccountViewsController : Controller
    {
        [HttpGet] public IActionResult AccountsIndex() => View();

        [HttpGet] public IActionResult SearchAccount() => View();

        [HttpGet] public IActionResult DisplayAccountInfo(List<AccountModel> accountModel) => View(accountModel);

        [HttpGet] public IActionResult CreateAccount() => View();

        [HttpGet] public IActionResult DeleteAccount() => View();

        [HttpGet] public IActionResult SearchTransactions() => View();

        [HttpGet] public IActionResult DisplayTransactions(TransactionsModel transactions) => View(transactions);

    }
}

CustomerManagement App/EmployeePortal-UI/Views/AccountViews/AccountsIndex.cshtml
@{
    ViewData["Title"] = "Accounts Management";
}
<br />
<div class="text-center" id="window">
    <h2 style="font-size:22px;color:red;">Accounts</h2>
    <br />
    <br />
    <a id="button" asp-controller="AccountViews" asp-action="SearchAccount">Search Account</a>
    <a id="button" asp-controller="AccountViews" asp-action="SearchTransactions">Search Transactions</a>
    <a id="button" asp-controller="AccountViews" asp-action="CreateAccount">Create Account</a>
    <a id="button" asp-controller="AccountViews" asp-action="DeleteAccount">DeleteAccount</a>
    <br />
    <br />
    <br />
   
</div>

CustomerManagement App/EmployeePortal-UI/Views/AccountViews/CreateAccount.cshtml
@model InsertAccountModel
@{
    ViewData["Title"] = "Create Account";
}

<br />
<div id="window" class="text-center">
    <br />
    <h2 style="font-size:22px;color:red;">Create Account</h2>
    <br />
    <br />
    <form method="post" asp-controller="AccountPostActions" asp-action="InsertAccount">
        <input id="textBox" asp-for="@Model.CustomerName" placeholder="Enter Customer Name" />
        <br />
        <b>@Html.ValidationMessageFor(model=>model.CustomerName,"" , new{ @class="text-danger"} ) </b>
        <br />
        <input id="textBox" asp-for="@Model.AccountName" placeholder="Enter Account Name" />
        <br />
        <b>@Html.ValidationMessageFor(model=>model.AccountName,"" , new{ @class="text-danger"} ) </b>
        <br />
        <input id="textBox" asp-for="@Model.TypeOfAccount" placeholder="Enter Type Of Account" />
        <br />
        <b>@Html.ValidationMessageFor(model=>model.TypeOfAccount,"" , new{ @class="text-danger"} ) </b>
        <br />
        <input id="textBox" asp-for="@Model.Ballance" placeholder="Enter Ballance" />
        <br />
        <b>@Html.ValidationMessageFor(model=>model.Ballance,"" , new{ @class="text-danger"} ) </b>
        <br />
        <input id="button" type="submit" placeholder="Create Account" />
    </form>

    <br />
    <br />
    <br />
</div>

CustomerManagement App/EmployeePortal-UI/Views/AccountViews/DeleteAccount.cshtml
@model DeleteAccountModel
@{

}
<br />
<div id="window" class="text-center">
    <br />
    <h2 style="font-size:22px;color:red;">Delete Customer</h2>
    <br />
    <br />
    <form method="post" asp-controller="AccountPostActions" asp-action="DeleteAccount">
        <input  id="deleteBox" asp-for="@Model.CustomerName" placeholder="Enter Customer Name" />
        <br />
        <b>@Html.ValidationMessageFor(model=>model.CustomerName,"",new{@class="text-danger"})</b>
        <br />
        <input  id="deleteBox" asp-for="@Model.AccountName" placeholder="Enter Account Name" />
        <br />
        <b>@Html.ValidationMessageFor(model=>model.AccountName,"",new{@class="text-danger"})</b>
        <br />
        <input  id="deleteBox" asp-for="@Model.TypeOfAccount" placeholder="Enter Type Of Account" />
        <br />
        <b>@Html.ValidationMessageFor(model=>model.TypeOfAccount,"",new{@class="text-danger"})</b>
        <br />
       <input   id="button" type="submit" placeholder="Search Customer" />
    </form>
    <br />
    <br />
</div>
<br />

CustomerManagement App/EmployeePortal-UI/Views/AccountViews/DisplayAccountInfo.cshtml
@model List<AccountModel>
@{
    ViewData["Title"] = "Account Info";
}
<br />
<div id="window">
    <br />
    <table style="border:solid;border-color:dodgerblue;margin-left:auto;margin-right:auto">
        <thead>
            <tr style="background-color:black;color:aliceblue;text-align:center;font-size:24px;">
                <td id="tableCell"> Account Owner Name </td>
                <td id="tableCell"> Account Name </td>
                <td id="tableCell"> Account Number </td>
                <td id="tableCell"> Account IBAN </td>
                <td id="tableCell"> Account Ballance </td>
            </tr>
        </thead> @foreach (var item in Model)
        {
            <tr style="color:red;text-align:center;font-size:24px">
                <td id="tableCell"> @item.AccountOwnerName </td>
                <td id="tableCell"> @item.AccountName </td>
                <td id="tableCell"> @item.AccountNumber </td>
                <td id="tableCell"> @item.AccountIBAN </td>
                <td id="tableCell"> @item.AccountBallance </td>
            </tr>
        }
    </table>
    <br />
    <br />
    <br />
    <br />
    <a id="button" asp-action="AccountsIndex" asp-controller="AccountViews"> Accounts Index </a>
    <br />
    <br />
</div>
<br />

CustomerManagement App/EmployeePortal-UI/Views/AccountViews/DisplayTransactions.cshtml
@model TransactionsModel
@{
    var customer = ViewData["Name"];

    ViewData["Title"] = $"{customer} - Display Transactions";

}

<br />
<div id="window">
    <br />
    <p style="font-size:26px;color:red;text-align:center">ATM Transactions</p>
    <table style="border:solid;border-color:dodgerblue;margin-left:auto;margin-right:auto">
        <thead>
            <tr id="tableHead">
                <td id="tableCell"> Type Of Transaction </td>
                <td id="tableCell"> Account Used </td>
                <td id="tableCell"> Amount </td>
                <td id="tableCell"> Transactions Date </td>
            </tr>
        </thead> @foreach (var atmTransaction in Model.AtmTransactions)
        {
            <tr id="tableCellRed">
                <td id="tableCell"> @atmTransaction.TypeOfTransaction </td>
                <td id="tableCell"> @atmTransaction.AccountUsed </td>
                <td id="tableCell"> @atmTransaction.Amount </td>
                <td id="tableCell"> @atmTransaction.TransactionDate </td>
            </tr>
        }
    </table>
    <br />
    <p style="font-size:26px;color:red;text-align:center">Income Transactions</p>
    <table style="border:solid;border-color:dodgerblue;margin-left:auto;margin-right:auto">
        <thead>
            <tr id="tableHead">
                <td id="tableCell"> Type Of Transfer </td>
                <td id="tableCell"> Account Used </td>
                <td id="tableCell"> Sender </td>
                <td id="tableCell"> Amount </td>
                <td id="tableCell"> Transactions Date </td>
            </tr>
        </thead> @foreach (var incomeTransaction in Model.IncomeTransactions)
        {
            <tr id="tableCellRed">
                <td id="tableCell"> @incomeTransaction.TypeOfTransfer </td>
                <td id="tableCell"> @incomeTransaction.AccountUsed </td>
                <td id="tableCell"> @incomeTransaction.Sender </td>
                <td id="tableCell"> @incomeTransaction.Amount </td>
                <td id="tableCell"> @incomeTransaction.TransactionDate </td>
            </tr>
        }
    </table>
    <br />
    <p style="font-size:26px;color:red;text-align:center">Outcome Transactions</p>
    <table style="border:solid;border-color:dodgerblue;margin-left:auto;margin-right:auto">
        <thead>
            <tr id="tableHead">
                <td id="tableCell"> Type Of Transfer </td>
                <td id="tableCell"> Account Used </td>
                <td id="tableCell"> Recipient </td>
                <td id="tableCell"> Amount </td>
                <td id="tableCell"> Transactions Date </td>
            </tr>
        </thead> @foreach (var outcomeTransaction in Model.OutcomeTransactions)
        {
            <tr id="tableCellRed">
                <td id="tableCell"> @outcomeTransaction.TypeOfTransfer </td>
                <td id="tableCell"> @outcomeTransaction.AccountUsed </td>
                <td id="tableCell"> @outcomeTransaction.Recipient </td>
                <td id="tableCell"> @outcomeTransaction.Amount </td>
                <td id="tableCell"> @outcomeTransaction.TransactionDate </td>
            </tr>
        }
    </table>
    <br />
    <br />
    <br />
    <br />
    <a id="button" asp-action="AccountsIndex" asp-controller="AccountViews"> Accounts Index </a>
    <br />
    <br />
</div>
<br />

CustomerManagement App/EmployeePortal-UI/Views/AccountViews/SearchAccount.cshtml
@model SearchModel
@{
    ViewData["Title"] = "Search Account";
}
<br />
<div id="window" class="text-center">
    <br />
    <h2 style="font-size:22px;color:red;">Search Account</h2>
    <br />
    <br />
    <form method="post" asp-controller="AccountPostActions" asp-action="SearchAccount">
        <input  id="textBox" asp-for="@Model.CustomerName" placeholder="Enter Customer Name" />
        <input  id="button" type="submit" placeholder="Search Customer" />
    </form>
    <br />
    <b>@Html.ValidationMessageFor(model=>model.CustomerName,"",new{@class="text-danger"})</b>
    <br />
    <br />
</div>
<br />

CustomerManagement App/EmployeePortal-UI/Views/AccountViews/SearchTransactions.cshtml
@model SearchModel
@{
    ViewData["Title"]= "Search Transactions";
}

<br />
<div id="window" class="text-center">
    <br />
    <h2 style="font-size:22px;color:red;">Search Transactions</h2>
    <br />
    <br />
    <form method="post" asp-controller="AccountPostActions" asp-action="SearchTransactions">
        <input id="textBox" asp-for="@Model.CustomerName" placeholder="Enter Customer Name" />
        <input  id="button" type="submit" placeholder="Search Customer" />
    </form>
    <br />
    <b>@Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })</b>
    <br />
    <br />

</div>
<br />