CustomerManagement App/EmployeePortal-UI/Controllers/FunctionsViewController.cs
using Microsoft.AspNetCore.Mvc;


namespace EmployeePortal_UI.Controllers
{
    public class FunctionsViewController : Controller
    {
        [HttpGet] public IActionResult FunctionsIndex() => View();

        [HttpGet] public IActionResult AccountStatement() => View();

        [HttpGet] public IActionResult PinCodeRegeneration() => View();

    }
}

CustomerManagement App/EmployeePortal-UI/Views/FunctionsView/AccountStatement.cshtml
@model StatementModel
@{
    ViewData["Title"] = "Account Statement";
}

<br />
<div id="window" class="text-center">
    <br />
    <h2 style="font-size:22px;color:red;">Account Statement</h2>
    <br />
    <form method="post" asp-controller="FunctionsPostActions" asp-action="DownloadStatement">
        <input id="textBox" asp-for="@Model.CustomerName" placeholder="Enter Customer Name" />
        <br />
        <b>@Html.ValidationMessageFor(model=>model.CustomerName,"",new{@class="text-danger"})</b>
        <br />
        <input  id="textBox" asp-for="@Model.AccountName" placeholder="Enter Account Name" />
        <br />
        <b>@Html.ValidationMessageFor(model=>model.AccountName,"",new{@class="text-danger"})</b>
        <br />
        <input  id="textBox" asp-for="@Model.AccountIBAN" placeholder="Enter Account IBAN" />
        <br />
        <b>@Html.ValidationMessageFor(model=>model.AccountIBAN,"",new{@class="text-danger"})</b>
        <br />
        <input  id="button" type="submit" placeholder="Regenerate Pin Code"/>
    </form>

    <br />
    <br />
    <br />
</div>

CustomerManagement App/EmployeePortal-UI/Views/FunctionsView/FunctionsIndex.cshtml
@{
    ViewData["Title"] = "Functions";
}

<br />
<div id="window" class="text-center">
    <br />
    <h2 style="font-size:22px;color:red;">CUSTOMER DATA MANAGEMENT</h2>
    <br />
    <a id="button" asp-controller="FunctionsView" asp-action="AccountStatement">Account Statements</a>
    <a id="button" asp-controller="FunctionsView" asp-action="PinCodeRegeneration">Pin Code Regeneration</a>
    <br />
    <br />
    <br />
</div>

CustomerManagement App/EmployeePortal-UI/Views/FunctionsView/PinCodeRegeneration.cshtml
@model SearchModel
@{
    ViewData["Title"] = "Pin Code Regeneration";
}

<br />
<div id="window" class="text-center">
    <br />
    <h2 style="font-size:22px;color:red;">Pin Code Regeneration</h2>
    <br />
    <form method="post" asp-controller="FunctionsPostActions"  asp-action="RegeneratePinCode">
        <input id="textBox" asp-for="@Model.CustomerName" placeholder="Enter Customer Name" />
        <input id="button" type="submit" placeholder="Regenerate Pin Code" />
    </form>
    <br />
    <b>@Html.ValidationMessageFor(model=>model.CustomerName,"",new{@class="text-danger"})</b>
    <br />
    <br />
    <br />
</div>