CustomerManagement App/EmployeePortal-UI/Controllers/CustomerViewsController.cs
using EmployeePortal_UI.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmployeePortal_UI.Controllers
{
    public class CustomerViewsController : Controller
    {
        [HttpGet] public IActionResult CustomerManagementIndex() => View();

        [HttpGet] public IActionResult SearchCustomer() => View();

        [HttpGet] public IActionResult AddCustomer() => View();

        [HttpGet] public IActionResult UpdateCustomerIndex() => View();

        [HttpGet] public IActionResult UpdateCustomerName() => View();

        [HttpGet] public IActionResult UpdateCustomerPhoneNumber() => View();

        [HttpGet] public IActionResult UpdateCustomerEmail() => View();

        [HttpGet] public IActionResult DeleteCustomer() => View();

        [HttpGet] public IActionResult DisplayCustomers(InsertCustomerModel customer) => View(customer);

    }
}

CustomerManagement App/EmployeePortal-UI/Views/CustomerViews/AddCustomer.cshtml
@model InsertCustomerModel
@{

}
<br />
<div id="window" class="text-center">
    <br />
    <h2 style="font-size:22px;color:red;">ADD NEW CUSTOMER</h2>
    <br />
    <br />
    <form method="post"  asp-controller="CustomerPostActions" asp-action="InsertCustomer">
        <input id="textBox" asp-for="@Model.CustomerName" placeholder="Enter Customer Name"/>
        <br />
        <b>@Html.ValidationMessageFor(model=>model.CustomerName,"" , new{ @class="text-danger"} ) </b>
        <br />
        <input id="textBox" asp-for="@Model.CustomerEmail" placeholder="Enter Customer Email"/>
        <br />
        <b>@Html.ValidationMessageFor(model=>model.CustomerEmail,"" , new{ @class="text-danger"} ) </b>
        <br />
        <input id="textBox" asp-for="@Model.CustomerPhoneNumber" placeholder="Enter Customer Phone Number"/>
        <br />
        <b>@Html.ValidationMessageFor(model=>model.CustomerPhoneNumber,"" , new{ @class="text-danger"} ) </b>
        <br />
        <input id="textBox" asp-for="@Model.AccountName" placeholder="Enter Account Name"/>
        <br />
        <b>@Html.ValidationMessageFor(model=>model.AccountName,"" , new{ @class="text-danger"} ) </b>
        <br />
        <input id="button" type="submit" placeholder="Add Customer" />
    </form>

    <br />
    <br />
    <br />
</div>

CustomerManagement App/EmployeePortal-UI/Views/CustomerViews/CustomerManagementIndex.cshtml
@{
    ViewData["Title"] = "Customer Data Management";
}

<br />
<div id="window" class="text-center">
    <br />
    <h2 style="font-size:22px;color:red;">CUSTOMER DATA MANAGEMENT</h2>
    <br />
    <a id="button" asp-controller="CustomerViews" asp-action="SearchCustomer" >Search Customer</a>
    <a id="button" asp-controller="CustomerViews" asp-action="AddCustomer">Add New Customer</a>
    <a id="button" asp-controller="CustomerViews" asp-action="UpdateCustomerIndex">Update Customer</a>
    <a id="button" asp-controller="CustomerViews" asp-action="DeleteCustomer">Delete Customer</a>
    <br />
    <br />
    <br />
</div>

CustomerManagement App/EmployeePortal-UI/Views/CustomerViews/DeleteCustomer.cshtml
@model DeleteCustomerModel
@{

}
<br />
<div id="window" class="text-center">
    <br />
    <h2 style="font-size:22px;color:red;">Delete Customer</h2>
    <br />
    <br />
    <form method="post" asp-controller="CustomerPostActions" asp-action="DeleteCustomerData">
        <input  id="deleteBox" asp-for="@Model.CustomerName" placeholder="Enter Customer Name" />
        <input  id="button" type="submit" placeholder="Search Customer" />
    </form>
    <br />
    <b>@Html.ValidationMessageFor(model=>model.CustomerName,"",new{@class="text-danger"})</b>
    <br />
    <br />
</div>
<br />

CustomerManagement App/EmployeePortal-UI/Views/CustomerViews/DisplayCustomers.cshtml
@model InsertCustomerModel
@{
    ViewData["Title"] = "Display Customers";
}

<br />
<div id="window">
  <br />
  <table style="border:solid;border-color:dodgerblue;margin-left:auto;margin-right:auto">
    <thead>
      <tr id="tableHead">
                <td id="tableCell"> Customer Name </td>
                <td id="tableCell"> Customer Email </td>
                <td id="tableCell"> Customer Phone Number </td>
      </tr>
    </thead>
    <tr style="color:red;text-align:center;font-size:24px">
            <td id="tableCell"> @Model.CustomerName </td>
            <td id="tableCell"> @Model.CustomerEmail </td>
            <td id="tableCell"> @Model.CustomerPhoneNumber </td>
    </tr>
  </table>
  <br />
  <br />
  <br />
  <br />
  <a id="button" asp-action="CustomerManagementIndex" asp-controller="CustomerViews"> Customer Management </a>
  <br />
  <br />
  <br />
</div>
<br />

CustomerManagement App/EmployeePortal-UI/Views/CustomerViews/SearchCustomer.cshtml
@model SearchModel
@{
    ViewData["Title"] = "Search Customer";
}

<br />
<div id="window" class="text-center">
    <br />
    <h2 style="font-size:22px;color:red;">Search Customer</h2>
    <br />
    <br />
    <form method="post" asp-controller="CustomerPostActions" asp-action="GetCustomers">
        <input id="textBox" asp-for="@Model.CustomerName" placeholder="Enter Customer Name" />
        <input  id="button" type="submit" placeholder="Search Customer" />
    </form>
    <br />
    <b>@Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })</b>
    <br />
    <br />

</div>
<br />

CustomerManagement App/EmployeePortal-UI/Views/CustomerViews/UpdateCustomerEmail.cshtml
@model UpdateCustomerEmailModel

@{
    ViewData["Title"] = "Update Customer Email";
}

<br />
<div id="window" class="text-center">
    <br />
    <h2 style="font-size:22px;color:red;">Update Customer Email</h2>
    <br />
    <br />
    <form method="post" asp-controller="CustomerPostActions" asp-action="UpdateCustomerEmail">
        <input id="updateBox" asp-for="@Model.CustomerName" placeholder="Enter Customer Name" />
        <br />
        <b>@Html.ValidationMessageFor(model=>model.CustomerName,"", new{@class="text-danger"})</b>
        <br />
        <input id="updateBox" asp-for="@Model.CustomerEmail" placeholder="Enter New Customer Email" />
        <br />
        <b>@Html.ValidationMessageFor(model=>model.CustomerEmail,"", new{@class="text-danger"})</b>
        <br />
        <input id="button" type="submit" placeholder="Update Email" />
    </form>
    <br />
    <br />
</div>
<br />

CustomerManagement App/EmployeePortal-UI/Views/CustomerViews/UpdateCustomerIndex.cshtml
@{

}

<br />
<div id="window" class="text-center">
    <br />
    <h2 style="font-size:22px;color:red;">UPDATE CUSTOMER</h2>
    <h6 style="font-size:22px;color:red;">-Choose Item-</h6>
    <br />
    <br />
    <a id="button" asp-controller="CustomerViews" asp-action="UpdateCustomerName">Update Customer Name</a>
    <a id="button" asp-controller="CustomerViews" asp-action="UpdateCustomerPhoneNumber">Update Phone Number</a>
    <a id="button" asp-controller="CustomerViews" asp-action="UpdateCustomerEmail">Update Customer Email</a>
    <br />
    <br />
    <br />
</div>

CustomerManagement App/EmployeePortal-UI/Views/CustomerViews/UpdateCustomerName.cshtml
@model UpdateCustomerNameModel
@{
    ViewData["Title"] = "Update Customer Name";
}

<br />
<div id="window" class="text-center">
    <br />
    <h2 style="font-size:22px;color:red;">Update Name</h2>
    <br />
    <br />
    <form method="post" asp-controller="CustomerPostActions" asp-action="UpdateCustomerName">
        <input id="updateBox" asp-for="@Model.CustomerName" placeholder="Enter Customer Name" />
        <br />
        <b>@Html.ValidationMessageFor(model=>model.CustomerName, "", new{@class="text-danger"})</b>
        <br />
        <input id="updateBox" asp-for="@Model.NewCustomerName" placeholder="Enter New Customer Name" />
        <br />
        <b>@Html.ValidationMessageFor(model=>model.NewCustomerName ,"", new{@class="text-danger"})</b>
        <br />
        <input id="button" type="submit" placeholder="Update Customer" />
    </form>
    <br />
    <br />

</div>
<br />

CustomerManagement App/EmployeePortal-UI/Views/CustomerViews/UpdateCustomerPhoneNumber.cshtml
@model UpdateCustomerPhoneNumberModel
@{
    ViewData["Title"] = "Update Customer Phone Number";
}

<br />
<div id="window" class="text-center">
    <br />
    <h2 style="font-size:22px;color:red;">Update Phone Number</h2>
    <br />
    <br />
    <form method="post" asp-controller="CustomerPostActions" asp-action="UpdateCustomerPhoneNumber">
        <input id="updateBox" asp-for="@Model.CustomerName" placeholder="Enter Customer Name" />
        <br />
        <b>@Html.ValidationMessageFor(model=>model.CustomerName,"", new{@class="text-danger"})</b>
        <br />
        <input id="updateBox" asp-for="@Model.CustomerPhoneNumber" placeholder="Enter New Customer Phone Number" />
        <br />
        <b>@Html.ValidationMessageFor(model=>model.CustomerPhoneNumber,"", new{@class="text-danger"})</b>
        <br />
        <input id="button" type="submit" placeholder="Update Phone Number" />
    </form>
    <br />
    <br />

</div>
<br />