ATM/ATM UI/Models/DepositModel.cs
using System.ComponentModel.DataAnnotations;

namespace ATM_UI.Models
{
    public class DepositModel
    {
        [Required(ErrorMessage = "Account Name Cannot Be Null.")]
        public string? AccountOwnerName { get; set; }

        [Required(ErrorMessage = "Account Number Cannot Be Null.")]
        public string? AccountNumber { get; set; }

        [Required(ErrorMessage = "Account IBAN Cannot Be Null.")]
        public string? AccountIBAN { get; set; }

        [Required(ErrorMessage = "Amount Cannot Be Null.")]
        public int? Amount { get; set; }

    }
}

ATM/ATM UI/Models/ErrorViewModel.cs
namespace ATM_UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ATM/ATM UI/Models/LoginModel.cs
using System.ComponentModel.DataAnnotations;

namespace ATM_UI.Models
{
    public class LoginModel
    {
        [Required(ErrorMessage = "Customer name is required.")]
        public string? CustomerName { get; set; }

        [Required(ErrorMessage = "Pin code is requred.")]
        public int? PIN { get; set; }

        [Required(ErrorMessage = "Account number is required.")]
        public string? AccountNumber { get; set; }

    }
}

ATM/ATM UI/Models/SoldModel.cs
namespace ATM_UI.Models
{
    public class SoldModel
    {
        public string? AccountOwnerName { get; set; }

        public string? AccountNumber { get; set; }

        public string? AccountIBAN { get; set; }

        public int? Ballance { get; set; }

        public string? DateTime { get; set; }
    }
}

ATM/ATM UI/Models/WithdrawModel.cs
namespace ATM_UI.Models
{
    public class WithdrawModel : DepositModel
    {
    }
}

ATM/ATM UI/Controllers/HomeController.cs
using ATM_UI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ATM_UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ATM/ATM UI/Controllers/LoginController.cs
using ATM_UI.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net;
using System.Text;
using System.Web;

namespace ATM_UI.Controllers
{
    public class LoginController : Controller
    {
        private readonly HttpClient _httpClient;

        public LoginController()
        {
            _httpClient = new HttpClient();
        }

        [HttpGet]

        [Route("/ATM/Login")]
        public IActionResult LoginPage()
        {
            return View();
        }

        [HttpPost]

        public IActionResult LogIN(LoginModel loginModel)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("LoginPage");

            }

            var autorizationStatus = _httpClient.PostAsync("https://localhost:7004/ATM/Authorize", new StringContent(JsonConvert.SerializeObject(loginModel), Encoding.UTF8, "application/json")).Result;

            if (autorizationStatus.StatusCode is HttpStatusCode.Accepted)
            {
                var accountNumber = HttpUtility.UrlEncode(loginModel.AccountNumber);

                return Redirect($"/ATM/Operations/{loginModel.CustomerName}/{accountNumber}");

            }
            else if (autorizationStatus.StatusCode is HttpStatusCode.Forbidden)
            {
                return Redirect($"/LOGIN/Forbidden/{loginModel.CustomerName}/{loginModel.AccountNumber}");

            }
            else if (autorizationStatus.StatusCode is HttpStatusCode.UnprocessableEntity)
            {
                return RedirectToAction("LoginPage");
            }

            return Redirect("/InternalServerError");

        }

        [HttpGet]

        [Route("/LOGIN/Forbidden/{customerName}")]

        public IActionResult Forbidden(string customerName)
        {
            return View(new LoginModel() { CustomerName = customerName });
        }
    }
}

ATM/ATM UI/Controllers/OperationsController.cs
using ATM_UI.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using System.Web;
using System.Net;

namespace ATM_UI.Controllers
{
    public class OperationsController : Controller
    {
        private readonly HttpClient _httpClient;

        public OperationsController()
        {
            _httpClient = new HttpClient();
        }

        [HttpGet]

        [Route("ATM/Operations/{customerName}/{accountNumber}")]
        public IActionResult Operations(string customerName, string accountNumber)
        {
            var accountInfo = _httpClient.GetStringAsync($"https://localhost:7004/ATM/Sold/{customerName}/{HttpUtility.UrlEncode(accountNumber)}").Result;

            var soldData = JsonConvert.DeserializeObject<SoldModel>(accountInfo);

            return View(soldData);
        }


        [HttpGet]

        [Route("ATM/Sold")]
        public IActionResult Sold()
        {
            return View();
        }

        [HttpGet]

        public IActionResult Deposit()
        {
            return View();
        
        }

        [HttpGet]

        public IActionResult Withdraw()
        {
            return View();
        }


        [HttpPost]
        public IActionResult DepositBallance(DepositModel depositModel)
        {
            if (!ModelState.IsValid)
            {
                return Redirect("/Error");
            }

            var depositResult = _httpClient.PostAsync("https://localhost:7004/ATM/Deposit",new StringContent(JsonConvert.SerializeObject(depositModel),Encoding.UTF8, "application/json")).Result;

            if (depositResult.StatusCode is HttpStatusCode.OK)
            {
                return Redirect("/Succes");
               
            }
            else if (depositResult.StatusCode is HttpStatusCode.NotFound)
            {
                return Redirect("/CustomerNotFound");
            }

            return Redirect("/Error");
        }


        [HttpPost]
        public IActionResult WithdrawBallance(WithdrawModel withdrawModel)
        {
            if (!ModelState.IsValid)
            {
                return Redirect("/Error");
            }

            var withdrawResult = _httpClient.PostAsync("https://localhost:7004/ATM/Withdraw", new StringContent(JsonConvert.SerializeObject(withdrawModel), Encoding.UTF8, "application/json")).Result;

            if (withdrawResult.StatusCode is HttpStatusCode.OK)
            {
                return Redirect("/Succes");
            }
            else if (withdrawResult.StatusCode is HttpStatusCode.NotFound)
            {
                return Redirect("/CustomerNotFound");
            }

            return Redirect("/Error");
        }


    }
}

ATM/ATM UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}


<div style="margin-top:20px;margin-bottom:20px;text-align:center;">
   <a style="font-size:40px;text-decoration:none;background-color:aliceblue;"  asp-controller="Login" asp-action="LoginPage">Enter PIN</a>
    
</div>

ATM/ATM UI/Views/Login/Forbidden.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model LoginModel
@{

}

<div style="margin-left:auto;margin-right:auto;text-align:center;">
    <p style="color:red;font-size:40px">User <b>@Model.CustomerName </b> is unautorized.</p>
</div>

ATM/ATM UI/Views/Login/LoginPage.cshtml
@model LoginModel

@{
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}

<div style="margin-left:auto;margin-right:auto;text-align:center;">
<form method="post" asp-action="LogIN">
        <label style="font-size:28px;background-color:aliceblue"><b>Enter Name And PIN Below</b></label>
    <br />
    <br />
        <input asp-for="@Model.CustomerName" placeholder="Enter your Name" style="font-size:24px;border:solid;border-color:turquoise"/>
    <br />
    <br />
        <input asp-for="@Model.AccountNumber" placeholder="Enter your Account Number" style="font-size:24px;border:solid;border-color:turquoise" />
    <br />
    <br />
        <input asp-for="@Model.PIN" placeholder="Enter your PIN" style="font-size:24px;border:solid;border-color:turquoise" />
    <br />
    <br />
        <input type="submit" placeholder="LOG IN" style="font-size:22px;border:solid;border-color:turquoise" />

</form>

</div>

ATM/ATM UI/Views/Operations/Deposit.cshtml
@model DepositModel
@{
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
<script>
    var customerName = localStorage.getItem("CustomerName");
    var accountNumber = localStorage.getItem("AccountNumber");
    var accountIBAN = localStorage.getItem("AccountIBAN");
    
    function Deposit(){

        var depositModel ={

            AccountOwnerName:customerName,
            AccountNumber:accountNumber,
            AccountIBAN:accountIBAN,
            Amount: $('#amountBox').val()

        };
        SendRequest(depositModel);
    };

    function SendRequest(object) {

        $.ajax({

            url: "DepositBallance",
            method:"POST",
            data:object,
            succes:function(data){
                data=JSON.parse(data);
                console.log(data);
            },
            error:function(err){
                console.log(err);
            }

        })
    }
       

    
</script>

<div>
    <form method="post" asp-action="DepositBallance">
        <label style="font-size:24px;text-align:center;background-color:aliceblue">Enter Amount To Deposit</label>
        <br />
        <br />
        <input  id="amountBox" asp-for="@Model.Amount" placeholder="Enter Amount Here." style="background-color:aliceblue;border:solid;border-color:turquoise"/>
        <br />
        <br />
    </form>
    <input type="submit" placeholder="Deposit" onclick="Deposit()" style="background-color:aliceblue;border:solid;border-color:turquoise" />
   
</div>

ATM/ATM UI/Views/Operations/Operations.cshtml
@model SoldModel
@{
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}

<script>
    localStorage.setItem("CustomerName", "@Model.AccountOwnerName");
    localStorage.setItem("AccountNumber", "@Model.AccountNumber");
    localStorage.setItem("AccountIBAN", "@Model.AccountIBAN");
    localStorage.setItem("Ballance", "@Model.Ballance");
    localStorage.setItem("DateTime", "@Model.DateTime");
</script>
<div style="text-align:center;">
   
    <a asp-controller="Operations" asp-action="Sold" style="font-size:24px;text-decoration:none;background-color:aliceblue;">SOLD</a>
    <a asp-controller="Operations" asp-action="Deposit" style="font-size:24px;width:20px;margin-left:200px;margin-top:-40px;text-decoration:none;background-color:aliceblue;">Deposit</a>
    <br />
    <a asp-controller="Operations" asp-action="Withdraw" style="font-size:24px;text-decoration:none;background-color:aliceblue;">Withdraw</a>
</div>

ATM/ATM UI/Views/Operations/Sold.cshtml
@{
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
    var dateTime = DateTime.Now.ToString("yyyy-MM-dd");
}

<script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
<script src="~/js/ShowDataScript.js"></script>

<div>
    <h1 style="color:red;text-align:center">Availabble Bllance:<span id="ballance" style="color:black"></span> </h1>
    <br />
    <br />
    <br />
    <p style="color:dodgerblue;text-align:left">Account Owner <span id="customerName" style="color:black"></span> </p>
    <br />
    <br />
    <p style="color:dodgerblue;text-align:left">Account IBAN <span id="accountIBAN" style="color:black"></span> </p>
    <br />
    <br />
    <p style="color:dodgerblue;text-align:left">Account Number <span id="accountNumber" style="color:black"></span> </p>
    <br />
    <br />
    <p style="color:dodgerblue;text-align:left">Date <span style="color:black"> @dateTime</span> </p>
</div>

ATM/ATM UI/Views/Operations/Withdraw.cshtml
@model WithdrawModel
@{
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
<script>
    var customerName = localStorage.getItem("CustomerName");
    var accountNumber = localStorage.getItem("AccountNumber");
    var accountIBAN = localStorage.getItem("AccountIBAN");

    function Deposit() {

        var depositModel = {

            AccountOwnerName: customerName,
            AccountNumber: accountNumber,
            AccountIBAN: accountIBAN,
            Amount: $('#amountBox').val()

        };
        SendRequest(depositModel);
    };

    function SendRequest(object) {

        $.ajax({

            url: "WithdrawBallance",
            method: "POST",
            data: object,
            succes: function (data) {
                data = JSON.parse(data);
                console.log(data);
            },
            error: function (err) {
                console.log(err);
            }

        })
    }

</script>

<div>
    <form method="post" asp-action="DepositBallance">
        <label style="font-size:24px;text-align:center;background-color:aliceblue">Enter Amount To Deposit</label>
        <br />
        <br />
        <input asp-for="@Model.Amount" id="amountBox" placeholder="Enter Amount Here." style="background-color:aliceblue;border:solid;border-color:turquoise" />
        <br />
        <br />
    </form>
    <input type="submit"  onclick="Deposit()"  style="margin-left:auto;margin-right:auto;background-color:aliceblue;border:solid;border-color:turquoise" placeholder="Deposit" />
</div>

ATM/ATM UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ATM_UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ATM_UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ATM_UI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Romanian BANK ATM  - Every Fraud Or Ilegall Activity Will Be Punished According With The Law
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ATM/ATM UI/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ATM_UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ATM_UI.styles.css" asp-append-version="true" />
</head>
<body>
   <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <h1 style="margin-left:auto;margin-right:auto;color:dodgerblue">WELCOME TO ROMANIAN BANK</h1>
            </div>
        </nav>
   </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Romanian BANK ATM  - Every Fraud Or Ilegall Activity Will Be Punished According The Law.
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>